CREATE TABLE DAILY_BATCH 
(
  JAR_NAME VARCHAR2(20) NOT NULL 
, NOTE VARCHAR2(40) NOT NULL 
, HOUR VARCHAR2(2) NOT NULL 
, MINUTE VARCHAR2(2) NOT NULL 
, WAITING_JAR VARCHAR2(20)
, PRIMARY KEY (JAR_NAME)
);

CREATE TABLE MONTHLY_BATCH 
(
  JAR_NAME VARCHAR2(20) NOT NULL 
, NOTE VARCHAR2(40) NOT NULL 
, DAY VARCHAR(2) NOT NULL 
, HOUR VARCHAR2(2) NOT NULL 
, MINUTE VARCHAR2(2) NOT NULL 
, WAITING_JAR VARCHAR2(20)
, PRIMARY KEY (JAR_NAME)
);

CREATE TABLE YEARLY_BATCH 
(
  JAR_NAME VARCHAR2(20) NOT NULL 
, NOTE VARCHAR2(40) NOT NULL 
, MONTH VARCHAR(2) NOT NULL 
, DAY VARCHAR(2) NOT NULL 
, HOUR VARCHAR2(2) NOT NULL 
, MINUTE VARCHAR2(2) NOT NULL 
, WAITING_JAR VARCHAR2(20)
, PRIMARY KEY (JAR_NAME)
);