CREATE TABLE DAILY_BATCH 
(
  ID VARCHAR2(4) NOT NULL 
, JAR_NAME VARCHAR2(20) NOT NULL 
, NOTE VARCHAR2(40) NOT NULL 
, HOUR VARCHAR2(2) NOT NULL 
, MINUTE VARCHAR2(2) NOT NULL 
, WAITING_BATCH_ID VARCHAR2(20) 
, PRIMARY KEY (ID)
);